<?php
/**
 * CodatDataContractsDatasetsProfitAndLossReportTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\CodatPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CodatDataContractsDatasetsProfitAndLossReportTest Class Doc Comment
 *
 * @category    Class
 * @description CodatDataContractsDatasetsProfitAndLossReport
 * @package     TheLogicStudio\CodatPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CodatDataContractsDatasetsProfitAndLossReportTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CodatDataContractsDatasetsProfitAndLossReport"
     */
    public function testCodatDataContractsDatasetsProfitAndLossReport()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_date"
     */
    public function testPropertyFromDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_date"
     */
    public function testPropertyToDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "income"
     */
    public function testPropertyIncome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_of_sales"
     */
    public function testPropertyCostOfSales()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gross_profit"
     */
    public function testPropertyGrossProfit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "expenses"
     */
    public function testPropertyExpenses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "net_operating_profit"
     */
    public function testPropertyNetOperatingProfit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_expenses"
     */
    public function testPropertyOtherExpenses()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_income"
     */
    public function testPropertyOtherIncome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "net_other_income"
     */
    public function testPropertyNetOtherIncome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "net_profit"
     */
    public function testPropertyNetProfit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
