<?php
/**
 * CodatPublicApiModelsDataProfitAndLossResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\CodatPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CodatPublicApiModelsDataProfitAndLossResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CodatPublicApiModelsDataProfitAndLossResponse
 * @package     TheLogicStudio\CodatPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CodatPublicApiModelsDataProfitAndLossResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CodatPublicApiModelsDataProfitAndLossResponse"
     */
    public function testCodatPublicApiModelsDataProfitAndLossResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reports"
     */
    public function testPropertyReports()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "report_basis"
     */
    public function testPropertyReportBasis()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "most_recent_available_month"
     */
    public function testPropertyMostRecentAvailableMonth()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "earliest_available_month"
     */
    public function testPropertyEarliestAvailableMonth()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
