<?php
/**
 * CodatClientsApiClientContractCompanySettingsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace TheLogicStudio\CodatPHP\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CodatClientsApiClientContractCompanySettingsTest Class Doc Comment
 *
 * @category    Class
 * @description CodatClientsApiClientContractCompanySettings
 * @package     TheLogicStudio\CodatPHP
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CodatClientsApiClientContractCompanySettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CodatClientsApiClientContractCompanySettings"
     */
    public function testCodatClientsApiClientContractCompanySettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_id"
     */
    public function testPropertyCompanyId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "offline_connector_install"
     */
    public function testPropertyOfflineConnectorInstall()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "one_time_sync"
     */
    public function testPropertyOneTimeSync()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
