<?php
/**
 * BillsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TheLogicStudio\CodatPHP\Test\Api;

use \TheLogicStudio\CodatPHP\Configuration;
use \TheLogicStudio\CodatPHP\ApiException;
use \TheLogicStudio\CodatPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillsApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdDataBillsBillIdAttachmentsAttachmentIdDownloadGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdDataBillsBillIdAttachmentsAttachmentIdDownloadGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdDataBillsBillIdAttachmentsAttachmentIdGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdDataBillsBillIdAttachmentsAttachmentIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdDataBillsBillIdAttachmentsGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdDataBillsBillIdAttachmentsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdPushBillsBillIdAttachmentsPost
     *
     * .
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdPushBillsBillIdAttachmentsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdPushBillsBillIdPut
     *
     * Posts an updated bill to the accounting package for a given company..
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdPushBillsBillIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdPushBillsPost
     *
     * Posts a new bill to the accounting package for a given company..
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdPushBillsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdDataBillsBillIdGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdDataBillsBillIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdDataBillsGet
     *
     * Gets the latest bills for a company, with pagination.
     *
     */
    public function testCompaniesCompanyIdDataBillsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
