<?php
/**
 * CompaniesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TheLogicStudio\CodatPHP\Test\Api;

use \TheLogicStudio\CodatPHP\Configuration;
use \TheLogicStudio\CodatPHP\ApiException;
use \TheLogicStudio\CodatPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CompaniesApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompaniesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdDelete
     *
     * Deletes a company, this is not reversible..
     *
     */
    public function testCompaniesCompanyIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdGet
     *
     * Fetch metadata on a single company..
     *
     */
    public function testCompaniesCompanyIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdPut
     *
     * Update a company with a new name and optional description.
     *
     */
    public function testCompaniesCompanyIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdSettingsGet
     *
     * Fetch settings on a single company..
     *
     */
    public function testCompaniesCompanyIdSettingsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdSettingsPut
     *
     * Update settings on a single company..
     *
     */
    public function testCompaniesCompanyIdSettingsPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdSyncSettingsGet
     *
     * .
     *
     */
    public function testCompaniesCompanyIdSyncSettingsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdSyncSettingsPost
     *
     * .
     *
     */
    public function testCompaniesCompanyIdSyncSettingsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesGet
     *
     * Fetch a list of all companies metadata with accounting links on the Codat platform.
     *
     */
    public function testCompaniesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesPost
     *
     * Initiate the process of onboarding a new company on the Codat platform.
     *
     */
    public function testCompaniesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
