<?php
/**
 * ConnectionApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TheLogicStudio\CodatPHP\Test\Api;

use \TheLogicStudio\CodatPHP\Configuration;
use \TheLogicStudio\CodatPHP\ApiException;
use \TheLogicStudio\CodatPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConnectionApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConnectionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdAuthorizationPut
     *
     * Put authorization information for a single data source connected to a single company..
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdAuthorizationPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdConnectionInfoBankFeedAccountsBankAccountIdPatch
     *
     * Update a single BankFeed BankAccount for a single data source connected to a single company..
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdConnectionInfoBankFeedAccountsBankAccountIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdConnectionInfoBankFeedAccountsGet
     *
     * Get BankFeed BankAccounts for a single data source connected to a single company..
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdConnectionInfoBankFeedAccountsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdConnectionInfoBankFeedAccountsPut
     *
     * Put BankFeed BankAccounts for a single data source connected to a single company..
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdConnectionInfoBankFeedAccountsPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdDelete
     *
     * Disconnect and delete a data source from a company.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdGet
     *
     * Retrieve a single data source connected to a single company, including its connection status.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdPatch
     *
     * Disconnect a data source from a company.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsGet
     *
     * Retrieve all data sources connected to a single company, including their connection statuses.
     *
     */
    public function testCompaniesCompanyIdConnectionsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdConnectionsPost
     *
     * Connect a data source to a company.
     *
     */
    public function testCompaniesCompanyIdConnectionsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
