<?php
/**
 * FilesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Codat API
 *
 * [See our API changes](https://docs.codat.io/changelog)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace TheLogicStudio\CodatPHP\Test\Api;

use \TheLogicStudio\CodatPHP\Configuration;
use \TheLogicStudio\CodatPHP\ApiException;
use \TheLogicStudio\CodatPHP\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  TheLogicStudio\CodatPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for companiesCompanyIdConnectionsConnectionIdFilesPost
     *
     * Upload files for a company.
     *
     */
    public function testCompaniesCompanyIdConnectionsConnectionIdFilesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdFilesDownloadGet
     *
     * Download all files for a company. You can specify a date to download specific files for..
     *
     */
    public function testCompaniesCompanyIdFilesDownloadGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for companiesCompanyIdFilesGet
     *
     * View all files uploaded by a specified company.
     *
     */
    public function testCompaniesCompanyIdFilesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
